spring:
  servlet:
    multipart:
      max-file-size: 10MB # 파일의 용량 제한
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(EsI3I93ZlhtYrYapS5oCJ4qYAEEZJu5U)
    username: ENC(nJZfcHF+It0X4f8rxo8Glg==)
    password: ENC(VhEaaBYxeXqSjYZZX+eq55lmU8vLdf4V)
  elasticsearch:
    uris: ENC(FpLrPai/YvcQTPM/M0aJb5MQBC0OYy2CR5OK2K+frmY=)
  data:
    redis:
      host: ENC(A+kwW2rkFaibUEBP1hchbA==)
      port: ${REDIS_PORT}
      password: ENC(xCySc7GekCOPVUEN6QG+L71ROBSch6oc)
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

cloud:
  aws:
    s3:
      servlet:
        multipart:
          max-file-size: 10MB  # 업로드 가능한 파일 크기
          max-request-size: 10MB
      bucket: daruda
    credentials:
      access-key: ENC(legTRlHg2eQ8A19FX7paqiS3xzZt+UekSmmVVbCDA2w=)
      secret-key: ENC(pB33J4FIwn6S6bSYlYeGusMeoNJVx0PgQdcppWrdWYU9adxYA+VOY7pkmc6oDeL3ACpQAZss2pw=)
    region: ap-northeast-2
    stack:
      auto: false

logging:
  file:
    path: ./daruda_log
  config: classpath:logback-spring.xml
  sentry:
    repository-uri: ${SENTRY_REPOSITORY_URI}
    environment: prod
    discord-webhook-url: ${DISCORD_WEBHOOK_URL}

kakao:
  client_id: 65b8edb9273b17a701f937868170f95e
  redirect_uri: https://daruda.site/api/v1/users/kakao/login-url

jwt:
  secret: ENC(KF614u6s2bd7ypduz4hAbdyn7toyBp9jKoD2TYu8Ib8lyhL7y6Z4ki8oWs0L0Z5VmNWrX1nTDw231//ko+wDdvQC9mk5Uf4f4McDZWhUlrBhTci6z/5scJ6Q4TYCMIONpPTgVX1HYnc=)
  access-token-expire-time: 10800000
  refresh-token-expire-time: 604800000

cookie:
  domain: ENC(9VZsfFJbFIMAnLwWJbLV4wRYgDK89y62)

sentry:
  dsn: ENC(L2Qt718YntVoAPXadfDDd7k5itveS5NfMBwjAE/BL1Blzz6LS+FzNQ1GHXnpXHWRCDk0o0ITmNL9M9ZeVDohhACWv24G7EcbSD10tyz5fC+cPHLJkxT1YG6b4PrPblsXvXuDpH5sJy8=)
  environment: prod
  servername: Daruda-prod
