spring:
  servlet:
    multipart:
      max-file-size: 10MB # 파일의 용량 제한
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(x/kKcAyeS+aMtsAM9rdO5zZwOOwkiOpGDHnpEDyQIsm5K+vkzBzBSBFtw/jpLH/QxNV+4g3bnWR0jhIIzH0xHvK5Qzqe6NUoH4BxmLuQNLJYnsGPmYKjh4cVSjd68YeIB05hz1vKQMA=)
    username: ENC(9CfN0UX4lMQ02BEMkG022A==)
    password: ENC(oYUwuas15PIV42nIXSIzNAnBNny8itI/)
  elasticsearch:
    uris: ENC(ada9m4mD7ta62j6wtiY3b3rzF/h7Lnck/gagfMzTo7k=)
  data:
    redis:
      host: ENC(oj+RdtNwLMK1Szhwnyuz5Q==)
      port: ${REDIS_PORT}
      password: ENC(Bp+5y/mBcWJ9pHYBCm67h7FCnyJuXvgL)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

cloud:
  aws:
    s3:
      servlet:
        multipart:
          max-file-size: 10MB  # 업로드 가능한 파일 크기
          max-request-size: 10MB
      bucket: daruda
    credentials:
      access-key: ENC(snr4At20t/yQs2mqS0QtmVJn5yORis6pzdm9tPzZbx4=)
      secret-key: ENC(Y70HFDrbcoTY8kTt0YZ8de0py4Dj5Cu1uCZ7h5w+NeDnymjOOpUuxGGAd+qdaEJc93jbeE37DiE=)
    region: ap-northeast-2
    stack:
      auto: false

logging:
  file:
    path: ./daruda_log
  config: classpath:logback-spring.xml
  sentry:
    repository-uri: ${SENTRY_REPOSITORY_URI}
    environment: dev
    discord-webhook-url: ${DISCORD_WEBHOOK_URL}

kakao:
  client_id: 65b8edb9273b17a701f937868170f95e
  redirect_uri: https://www.daruda.shop/api/v1/users/kakao/login-url

jwt:
  secret: ENC(Mzng6SahiZBXTfKCB6pdKIcdPTDMcAhJyyBjbwuSkNbbd9ysylQonYe7u4f3FYfQXYUXZJiC+k/fmUMYNzykCrFke+EloN7/1kt5PJiNPz8IFNDlm9j2BBr6q9wRU5pvxHj/oNOIVZg=)
  access-token-expire-time: 10800000
  refresh-token-expire-time: 604800000

cookie:
  domain: ENC(VE9qiI0hHnNbk0KEJS7VmM12as+NE9XR)

sentry:
  dsn: ENC(sG+5gVfk4gTxxw0NRQrPhl0ak5EFfvpBGTZvgnTPjBSvotGwmgfSBC1/XkawwcgbnQEGKXwCFStH+v2FyVGO+5JMNnjRUxjCAFLlL7FcYxQBExiYBIU+gBMgnKBn7Ww5jVZ4883qUy4=)
  environment: dev
  servername: Daruda-dev

admin:
  page:
    origin: ENC(05TI1WffZG09Nbhe4V77RSSdzXiSbIXVF8djjwlwTLEmXPpD16ryNg==)
